FROM python:3.9-slim

WORKDIR /app

COPY ./requirements.txt /app
RUN pip install -r requirements.txt


COPY ./config.py /app 
COPY ./models/label_encoder.joblib /app 
COPY ./models/trained_xgb.joblib /app 
COPY ./server.py /app 

EXPOSE 8501

CMD ["streamlit", "run", "streamlit_app.py"]